
extern zend_class_entry *phalcon_auth_remembertoken_remembertokeninterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_RememberToken_RememberTokenInterface);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_remembertoken_remembertokeninterface_gettoken, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_remembertoken_remembertokeninterface_getuseragent, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_remembertoken_remembertokeninterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Auth_RememberToken_RememberTokenInterface, getToken, arginfo_phalcon_auth_remembertoken_remembertokeninterface_gettoken)
	PHP_ABSTRACT_ME(Phalcon_Auth_RememberToken_RememberTokenInterface, getUserAgent, arginfo_phalcon_auth_remembertoken_remembertokeninterface_getuseragent)
	PHP_FE_END
};
