
extern zend_class_entry *phalcon_auth_remembertoken_rememberinginterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_RememberToken_RememberingInterface);

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_auth_remembertoken_rememberinginterface_getremembertoken, 0, 0, Phalcon\\Auth\\RememberToken\\RememberTokenInterface, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_auth_remembertoken_rememberinginterface_setremembertoken, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, value, Phalcon\\Auth\\RememberToken\\RememberTokenInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_remembertoken_rememberinginterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Auth_RememberToken_RememberingInterface, getRememberToken, arginfo_phalcon_auth_remembertoken_rememberinginterface_getremembertoken)
	PHP_ABSTRACT_ME(Phalcon_Auth_RememberToken_RememberingInterface, setRememberToken, arginfo_phalcon_auth_remembertoken_rememberinginterface_setremembertoken)
	PHP_FE_END
};
