
extern zend_class_entry *phalcon_auth_rememberinginterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_RememberingInterface);

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_auth_rememberinginterface_getremembertoken, 0, 0, Phalcon\\Auth\\RememberTokenInterface, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_auth_rememberinginterface_createremembertoken, 0, 0, Phalcon\\Auth\\RememberTokenInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_rememberinginterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Auth_RememberingInterface, getRememberToken, arginfo_phalcon_auth_rememberinginterface_getremembertoken)
	PHP_ABSTRACT_ME(Phalcon_Auth_RememberingInterface, createRememberToken, arginfo_phalcon_auth_rememberinginterface_createremembertoken)
	PHP_FE_END
};
