
extern zend_class_entry *phalcon_auth_events_eventinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_Events_EventInterface);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_events_eventinterface_gettype, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_events_eventinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Auth_Events_EventInterface, getType, arginfo_phalcon_auth_events_eventinterface_gettype)
	PHP_FE_END
};
